### ISSUE TITLE
Changing user from root

### ISSUE THREAD

**Issue by gitsf** [tiredofit/docker-insync#3] opened 2019-06-19 17:14 UTC
Do you know of a way to change this UID:GID of the user that runs insync?

I have tried changing the user when starting the docker using the -u flag, however it fails to start because of permission errors when trying to create the docker. It appears to be unable to copy over the install folder scripts.
I have also tried cloning your repository and modifying the dockerfile to have a USER block at the very end, after it copies files. However insync is unable to start.
I have kind of started trying to tweak the script files to see if I can get insync to run as a different user, but haven't had much luck yet. 
I am not familiar with the s6 overlay that appears to be what is scheduling when to run insync.
Figured before I wasted more hours on it I would ask in case you know the answer already.

The reason I am trying to accomplish this is so my Google Drive files are not owned by root:root, as they are now.
I know I could create a script on the local machine to run every so often and change owners, but I figured if I could just change what uid:gid the docker is using for insync this would solve it at the source.
Any help you have would be greatly appreciated.

**Comment by tiredofit** [comment] 2019-06-19 22:46
HI there, certainly. I just whipped up a new release tag `2.0` and `latest` that runs as the insync user, instead of root.

Inside the base image `tiredofit/debian:stretch` is functionality to change the UID and GID of the running user. So in this case, you would want to add two more environment variables to your docker-compose.yml.

````bash
USER_insync=1000
GROUP_insync=1000
````

Let me know how this works out.

**Comment by gitsf** [comment] 2019-06-20 04:22
It did not work, it appears the insync user uid:gid was changed successfully but there are permission errors within the docker.
I have deleted the contents of my mapped drives for /data and /root/.config/Insync
I then read through your changes about not using the config folder anymore, so I removed that mapping. The only part of these errors that change is the error from the Upgrade Catcher section.
The rest of the errors still remain.
Connecting into the docker and looking at some permissions, I see the /data directory is owned by insync:root
The /home/insync directory is owned by 12345:12345
That appears to be the default insync user's id's. So the folder is being created before the uid:gid change. Maybe need a change ownership line or something somewhere in there.

Thanks again for the quick help, let me know if you want any other info.

LOG From Docker
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-s6: applying...
[fix-attrs.d] 01-s6: exited 0.
[fix-attrs.d] 02-zabbix: applying...
[fix-attrs.d] 02-zabbix: exited 0.
[fix-attrs.d] 03-logrotate: applying...
[fix-attrs.d] 03-logrotate: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-permissions: executing...
**** [permissions] uid of user insync has been changed to 99.
**** [permissions] Total 1 UIDs modified
**** [permissions] gid of group insync has been changed to 100.
**** [permissions] total 1 GIDs modified
[cont-init.d] 01-permissions: exited 0.
[cont-init.d] 02-zabbix: executing...
**** [zabbix] Disabling Zabbix
[cont-init.d] 02-zabbix: exited 0.
[cont-init.d] 03-cron: executing...
**** [cron] Enabling Cron
[cont-init.d] 03-cron: exited 0.
[cont-init.d] 04-smtp: executing...
**** [smtp] Disabling SMTP Features
[cont-init.d] 04-smtp: exited 0.
[cont-init.d] 10-insync: executing...
/var/run/s6/etc/cont-init.d/10-insync: line 28: /root/.config/Insync: Is a directory
** [insync] Old version of Insync Image detected, copying files to new unified storage area. Please delete old volume mapping to

To add accounts in headless mode, use the "insync-headless add_account" command. Run "insync-headless help add_account" for more details.
** [insync] Sleeping 10 seconds..
[Errno 13] Permission denied: '/home/insync/.config'CRITICAL:root:while creating Client object
Traceback (most recent call last):
File "ideskmain/client.py", line 1004, in client_gevent_runner
File "ideskutils/gevent_itc.py", line 137, in wrapper
File "ideskutils/gevent_itc.py", line 37, in wrapper
File "ideskmain/client.py", line 58, in __init__
File "ideskmain/client.py", line 621, in __load_config
File "ideskfs/fs.py", line 222, in create_dir
File "os.py", line 150, in makedirs
File "os.py", line 157, in makedirs
OSError: [Errno 13] Permission denied: '/home/insync/.config'
Insync doesn't seem to be running. Start it first.

sudo: unknown user: insync-headless
sudo: unable to initialize policy plugin
Insync doesn't seem to be running. Start it first.

[cont-init.d] 10-insync: exited 0.
[cont-init.d] 99-container-init: executing...
[cont-init.d] 99-container-init: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
** [insync] To selectively sync specific folders, enter the container and execute "manage_sync"
** [insync] To manage your Ignored Files, enter the container and execute "manage_ignore"

** [insync] Starting insync-headless for xxxx@gmail.com
To add accounts in headless mode, use the "insync-headless add_account" command. Run "insync-headless help add_account" for more details.
CRITICAL:root:while creating Client object
Traceback (most recent call last):
File "ideskmain/client.py", line 1004, in client_gevent_runner
File "ideskutils/gevent_itc.py", line 137, in wrapper
File "ideskutils/gevent_itc.py", line 37, in wrapper
File "ideskmain/client.py", line 58, in __init__
File "ideskmain/client.py", line 621, in __load_config
File "ideskfs/fs.py", line 222, in create_dir
File "os.py", line 150, in makedirs
File "os.py", line 157, in makedirs
OSError: [Errno 13] Permission denied: '/home/insync/.config'
To add accounts in headless mode, use the "insync-headless add_account" command. Run "insync-headless help add_account" for more details.
CRITICAL:root:while creating Client object
Traceback (most recent call last):
File "ideskmain/client.py", line 1004, in client_gevent_runner
File "ideskutils/gevent_itc.py", line 137, in wrapper
File "ideskutils/gevent_itc.py", line 37, in wrapper
File "ideskmain/client.py", line 58, in __init__
File "ideskmain/client.py", line 621, in __load_config
File "ideskfs/fs.py", line 222, in create_dir
File "os.py", line 150, in makedirs
File "os.py", line 157, in makedirs
OSError: [Errno 13] Permission denied: '/home/insync/.config'
Insync doesn't seem to be running. Start it first.

** [insync] To selectively sync specific folders, enter the container and execute "manage_sync"
** [insync] To manage your Ignored Files, enter the container and execute "manage_ignore"
** [insync] Starting insync-headless for xxxx@gmail.com
Insync doesn't seem to be running. Start it first.

** [insync] To selectively sync specific folders, enter the container and execute "manage_sync"
** [insync] To manage your Ignored Files, enter the container and execute "manage_ignore"
** [insync] Starting insync-headless for xxxx@gmail.com
To add accounts in headless mode, use the "insync-headless add_account" command. Run "insync-headless help add_account" for more details.
CRITICAL:root:while creating Client object
Traceback (most recent call last):
File "ideskmain/client.py", line 1004, in client_gevent_runner
File "ideskutils/gevent_itc.py", line 137, in wrapper
File "ideskutils/gevent_itc.py", line 37, in wrapper
File "ideskmain/client.py", line 58, in __init__
File "ideskmain/client.py", line 621, in __load_config
File "ideskfs/fs.py", line 222, in create_dir
File "os.py", line 150, in makedirs
File "os.py", line 157, in makedirs
OSError: [Errno 13] Permission denied: '/home/insync/.config'
Insync doesn't seem to be running. Start it first.

**Comment by tiredofit** [comment] 2019-06-20 04:42
So close. I see it too. Just pushed `2.0.1` that I _did_ test :)

**Comment by gitsf** [comment] 2019-06-20 14:17
Not working for me

**Comment by tiredofit** [comment] 2019-06-20 14:25
`2.0.2` out - with a fix for Insync get-status. Terribly sorry about these releases, I'm rushing obviously to put them out and juggling too many other things on the go.

**Comment by gitsf** [comment] 2019-06-20 14:25
Not working for me, it doesn't seem to add the account.

I was able to connect in and run the commands manually to add the account and it says it was added successfully. However not sure how to get insync to start running

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-s6: applying...
[fix-attrs.d] 01-s6: exited 0.
[fix-attrs.d] 02-zabbix: applying...
[fix-attrs.d] 02-zabbix: exited 0.
[fix-attrs.d] 03-logrotate: applying...
[fix-attrs.d] 03-logrotate: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-permissions: executing...
**** [permissions] uid of user insync has been changed to 99.
**** [permissions] Total 1 UIDs modified
**** [permissions] gid of group insync has been changed to 100.
**** [permissions] total 1 GIDs modified
[cont-init.d] 01-permissions: exited 0.
[cont-init.d] 02-zabbix: executing...
**** [zabbix] Disabling Zabbix
[cont-init.d] 02-zabbix: exited 0.
[cont-init.d] 03-cron: executing...
**** [cron] Enabling Cron
[cont-init.d] 03-cron: exited 0.
[cont-init.d] 04-smtp: executing...
**** [smtp] Disabling SMTP Features
[cont-init.d] 04-smtp: exited 0.
[cont-init.d] 10-insync: executing...
To add accounts in headless mode, use the "insync-headless add_account" command. Run "insync-headless help add_account" for more details.
** [insync] Sleeping 10 seconds..
Proxy config set.
sudo: unknown user: insync-headless
sudo: unable to initialize policy plugin
Insync autostart enabled
[cont-init.d] 10-insync: exited 0.
[cont-init.d] 99-container-init: executing...
[cont-init.d] 99-container-init: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
** [insync] To selectively sync specific folders, enter the container and execute "manage_sync"
** [insync] To manage your Ignored Files, enter the container and execute "manage_ignore"

** [insync] Starting insync-headless for XXXX@gmail.com
To add accounts in headless mode, use the "insync-headless add_account" command. Run "insync-headless help add_account" for more details.
** [cron] Starting cron

**Comment by gitsf** [comment] 2019-06-20 14:26
Sorry I accidentally submitted my first comment about it not working. I see you just commented a new change. 
Let me try it.
I can't thank you enough for the quick responses to this. I really appreciate it.

**Comment by tiredofit** [comment] 2019-06-20 14:27
Hi Thanks, I saw your brief one liner "not working" in an email notification and went over it again with a clear head. I found one error which could be the cause for it not working. Unfortunately at this time the Docker Hub is clogged as I just pushed a new version of Alpine which in turn rebuilds approximately 70 other issues. Can you try to clone this repo and build locally for the time being?

**Comment by gitsf** [comment] 2019-06-20 15:10
Sorry for the delay, I cloned the repo and built it and it appears to be working perfectly.
Is it normal to connect into the docker and running any insync-headless commands show insync as not running? 
I was trying to view the sync progress info, and it says it isn't running. However if I look at my data folder it is growing because it is syncing in the background.

**Comment by tiredofit** [comment] 2019-06-20 15:32
Alright! Glad to hear its working.
Nice catch too, S6 Overlay runs as root, and I'm doing a bit of a hackish approach in regards to using it. Insync runs as the insync user but when you enter into the container with a `docker exec -it insync app bash` it spawns a root session. I added a quick alias to the `/root/.bashrc` file that switches to the insync user temporarily when executing the `insync-headless` command. Let me know if this works and then I think we're good to close this one off!

Tagged as `2.0.3`

**Comment by gitsf** [comment] 2019-06-20 16:06
That should fix it, I didn't even think about it being because I didn't change to the insync user when i entered the container. Haven't been able to test, since I am having issues getting it to close nicely.

I found another issue... Finish script needs to switch to insync user before 
I think I solved it and submitted it to you.

[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
Insync doesn't seem to be running. Start it first.

**Comment by tiredofit** [comment] 2019-06-20 17:12
No worries, I'm working as well. I've merged your pull and the latest release is 2.0.4. Your patch will definitely solve the ungracious exit issue.

**Comment by gitsf** [comment] 2019-06-20 17:59
OK, with all of those changes it appears to be working good!

**Comment by tiredofit** [comment] 2019-06-20 18:47
Fantastic! I'm a bit embarrassed at how fast I came out of the gate and left a whole bunch of errors each release. Thanks for the patience, and glad this is working out for you!

**Closed by tiredofit** 2019-06-20 18:47 UTC
